version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis_service:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  script_redis:
    build: ./redis
    depends_on:
      - redis_service
    environment:
      HOST_TO_REDIS: redis_service
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2GB"
    command: ["python", "PovoarRedis.py"]

  script_transferir:
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - script_redis
    environment:
      HOST_TO_REDIS: redis_service
      HOST_TO_POSTGRES: postgres
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2GB"
    command: ["sleep", "infinity"]

volumes:
  postgres_data:
  redis_data:
