services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2GB"

  script_redis:
    build: ./redis
    depends_on:
      - postgres
      - redis
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2GB"

volumes:
  postgres_data:
  redis_data: